name: Sync to AWS S3 and Invalidate CloudFront

on:
  push:
    paths:
      - 'website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Show Git Commit SHA
      run: echo "Running on commit ${{ github.sha }}"

    - name: Show Git Status
      run: git status

    - name: Show Git Log (Last Commit)
      run: git log -1 --pretty=oneline

    - name: Verify script.js content AFTER checkout
      run: |
        echo "--- Displaying content of website/script.js AFTER checkout ---"
        cat website/script.js || echo "ERROR: website/script.js not found or is empty AFTER checkout"
        echo "--- End of script.js content AFTER checkout ---"


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
  
    - name: Verify script.js content before sync
      run: |
        echo "--- Displaying content of website/script.js before sync ---"
        cat website/script.js || echo "ERROR: website/script.js not found or is empty"
        echo "--- End of script.js content ---"

    - name: Sync to S3
      run: |
        aws s3 sync website/ s3://${{ secrets.S3_BUCKET_NAME }}/ --acl public-read

    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
