name: Cypress Test and Terraform Apply

on:
  push:
    paths:
      - 'cypress/e2e/**'
      - '**/*.tf'

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: cypress/included:7.7.0

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clear Cypress Cache
      run: npx cypress cache clear

    - name: Install Cypress
      run: npm install cypress@13.6.4

    - name: Run Cypress tests
      run: npx cypress run --spec "cypress/e2e/spec.cy.js"

  terraform:
    runs-on: ubuntu-latest
    needs: test

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      run: |
        mkdir -p ~/.aws
        echo "[default]
        aws_access_key_id=${AWS_ACCESS_KEY_ID}
        aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}
        region=${AWS_REGION}
        " > ~/.aws/credentials

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
